# Generated by Django 5.1.7 on 2025-03-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='trailer',
            new_name='trailer_url',
        ),
    ]
