# Generated by Django 5.1.7 on 2025-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0002_rename_trailer_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Drama', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='mls.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
