# Generated by Django 5.1.7 on 2025-03-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mls', '0003_movie_genre_movie_rating_movie_recommendations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
